---
caddy:
  hosts:
    caddy:
      ansible_host: 192.168.1.105
      ansible_user: root
      # Caddy Configuration
      caddy_webdav_root: /var/www/webdav
      caddy_webdav_port: 8080
      caddy_domain: willfan.me
      
      # Reverse Proxy Targets
      caddy_reverse_proxies:
        - subdomain: homepage
          upstream: http://192.168.1.103:3000
        - subdomain: immich
          upstream: http://192.168.1.101:2283
        - subdomain: netbox
          upstream: http://192.168.1.104:8080
        - subdomain: anki
          upstream: http://192.168.1.100:8080
        - subdomain: proxmox
          upstream: https://192.168.1.50:8006
          insecure_skip_verify: true
