---
homepage:
  hosts:
    homepage-node:
      ansible_host: 192.168.1.103
      # Homepage dashboard configuration
      homepage_port: 3000
      proxmox_vmid: 103
      proxmox_node: pve0
      
      # Application Credentials (fill in securely)
      proxmox_api_user: "root@pam!homepage"
      proxmox_api_password: "{{ vault_proxmox_api_password_homepage }}"
      tailscale_device_id: "n9rsyfnzLp11CNTRL"
      tailscale_api_key: "{{ vault_tailscale_api_key_homepage }}"
      immich_api_key: "{{ vault_immich_api_key_homepage }}"
      
      # Tailscale Serve
      tailscale_proxy_target: "http://127.0.0.1:3000"
      
      # Allowed Hosts
      homepage_allowed_hosts: "*"
