---
homepage:
  hosts:
    homepage-node:
      ansible_host: 192.168.1.103
      # Homepage dashboard configuration
      homepage_port: 3000
      proxmox_vmid: 103
      proxmox_node: pve0
      
      # Application Credentials (fill in securely)
      proxmox_api_user: "root@pam!homepage"
      proxmox_api_password: "28b55958-24db-4698-a6b5-b7dc7f9af156"
      tailscale_device_id: "n9rsyfnzLp11CNTRL"
      tailscale_api_key: "tskey-api-kfCu8zoGxZ11CNTRL-wk6JXiuBsmKTWF621ycWmK1aHWxN8twoK"
      immich_api_key: "DRlBBIVhjywVSgPr8mFZT5qugiT490e1CQAvYk60"
