---
homepage:
  hosts:
    homepage-node:
      ansible_host: 192.168.1.103
      # Homepage dashboard configuration
      homepage_port: 3000
      
      # Application Credentials (fill in securely)
      proxmox_pve0_api_user: "root@pam!terraform"
      proxmox_pve0_api_password: "e095389a-ba15-48ea-b64e-54812523aa5b"
      proxmox_pve1_api_user: "PLACEHOLDER_USER"
      proxmox_pve1_api_password: "PLACEHOLDER_SECRET"
      proxmox_pve2_api_user: "PLACEHOLDER_USER"
      proxmox_pve2_api_password: "PLACEHOLDER_SECRET"
      immich_api_key: "DRlBBIVhjywVSgPr8mFZT5qugiT490e1CQAvYk60"
