---
# Handlers for Homepage role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Homepage
  ansible.builtin.systemd:
    name: homepage
    state: restarted
