---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Check if Netbox directory is a git repo
  stat:
    path: "{{ netbox_install_dir }}/.git"
  register: netbox_git_dir

- name: Remove existing non-git directory
  file:
    path: "{{ netbox_install_dir }}"
    state: absent
  when: not netbox_git_dir.stat.exists

- name: Clone Netbox Docker repository
  git:
    repo: "{{ netbox_git_repo }}"
    dest: "{{ netbox_install_dir }}"
    version: "{{ netbox_git_version }}"
    force: yes



- name: Create env directory
  file:
    path: "{{ netbox_install_dir }}/env"
    state: directory
    mode: '0755'

- name: Create environment files
  copy:
    dest: "{{ netbox_install_dir }}/env/{{ item.file }}"
    content: "{{ item.content }}"
  loop:
    - file: netbox.env
      content: |
        ALLOWED_HOSTS='*'
        DB_HOST=postgres
        DB_USER=netbox
        DB_PASSWORD=netbox
        REDIS_HOST=redis
        REDIS_PASSWORD=netbox
        REDIS_CACHE_HOST=redis-cache
        REDIS_CACHE_PASSWORD=netbox
    - file: postgres.env
      content: |
        POSTGRES_DB=netbox
        POSTGRES_USER=netbox
        POSTGRES_PASSWORD=netbox
    - file: redis.env
      content: |
        REDIS_PASSWORD=netbox
    - file: redis-cache.env
      content: |
        REDIS_PASSWORD=netbox

- name: Create docker-compose.override.yml
  copy:
    dest: "{{ netbox_install_dir }}/docker-compose.override.yml"
    content: |
      services:
        netbox:
          ports:
            - "{{ netbox_port }}:8080"
          healthcheck:
            start_period: 300s
          environment:
            - SECRET_KEY={{ lookup('password', 'credentials/netbox_secret.key length=50 chars=ascii_letters,digits') }}
            - SUPERUSER_NAME=admin
            - SUPERUSER_EMAIL=admin@example.com
            - SUPERUSER_PASSWORD=admin
            - SUPERUSER_API_TOKEN=0123456789abcdef0123456789abcdef01234567

- name: Pull Netbox images
  command: docker compose pull
  args:
    chdir: "{{ netbox_install_dir }}"

- name: Start Netbox
  command: docker compose up -d
  args:
    chdir: "{{ netbox_install_dir }}"
