---
netbox_git_repo: "https://github.com/netbox-community/netbox-docker.git"
netbox_git_version: "3.0.2"  # netbox-docker version for Netbox 4.1.x 注意这里和netbox本身版本不是一个东西
netbox_install_dir: "/opt/netbox-docker"
netbox_port: 8080
netbox_image: "netboxcommunity/netbox:v4.1.11"
netbox_superuser_name: "admin"
netbox_superuser_email: "admin@example.com"
netbox_superuser_password: "admin"
netbox_superuser_api_token: "0123456789abcdef0123456789abcdef01234567"
