---
all:
  children:
    proxmox_cluster:
    oci:
    esxi_hosts:
      children:

    tailscale:
      children:
        proxmox_cluster:
        oci:
        pve_lxc:
        pve_vms:

    pve_lxc:
    pve_vms:

