---
all:
  children:
    proxmox_cluster:
    oci:
    esxi_hosts:
    esxi_vms:
    tailscale:
      children:
        proxmox_cluster:
        oci:
        pve_lxc:
        pve_vms:
        esxi_vms:

    pve_lxc:
    pve_vms:

