#cloud-config
ssh_pwauth: true
preserve_hostname: false
manage_etc_hosts: true
hostname: netbox
users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0Nn62YvIZknVkIhRiLhVlsaEDOCZNV5SPABioYShTa/UKRpy19NUx9csv+Qiz2LDs6OB6aSUmY/SxffmI+PNgPM5iqv62qqOGwjqLpuuW6ItNLDAm+obL0nxT1+bb2xG9tTP54xL7e3rwK4/i4DF9VVEaXeZl3EiB2KUSjaslXBQ+3siiGQ+FIX2+/rQI7yqH2aVrBUXh559nkHb6EaZdqdmkoDeAObwswEesHi8A51Mfe3DErRKPHD2nmdpBkGUe+2AlI7OqX0/2CdbHv2y6jC/LOWz5wFDcmdMFG0uTcrbrdlwfnaerS1c54Exa4zLfcaoEhISJ+hH4G4SbfxzOO+MOF9Nox4Xrgoz0ctdWo3YiDSAiQuVzPNRIKpoD4Gv0xm/Q13Of4sUEPWQ7bx1v+BnpkkyQsKm3aWs+xJnY20gDGF/9+1rTS5Ey4vbye0zpi4WJvBGA+Y+U453RcAU0Azgs8FC4rmgYYzV7iZX0EPDxiexlXJTTcQQR0E9ijYkjM2nBDNj80FVRyAMt/dkwNITVe1jnTULN7X2kGeHK1Vy4nidG+AchsrCwj/0q9PkxIPsyukiF/n+IEAeTFrx+VoVhTPyFLHThfmdWneVyp3MTMhKPvqMsfiNq/vrA8O7257KIaR3uhjAlhfQU1DDYyAFDl2ChsqQ3W4F1EzrzUw== root@pve0
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLl1If2F9FzhwsAK/apQh99Qfwnjds8CUmTVd35PNbnb/2N+wXCNveacGLZeBHOyp/JmAyCO/u+WAY1ODb1X1D3gcXQ1CV2Wif2RUxRrScIVPKUlNGLQcDHEtnnEB9mb6E3LTLAm/i32jsAoHLxiYpwH8qFKjpaQgudXPuSSivFB+WCGupkF5rqJgzjYWxHtbHRQ2CWktxZ9Us5Mz9fi2j2iqgRP521wrMJw+jtuFsSTrHMWBLdlWRvB9VrWdRVDnf0xnv3zlXWZTUq3msgkLv0vuiw0qs9WxIq9AHHIAaoQHhsTz9y1nxWPA8pBrpvKQuKjkjIWvBnDT9E6PH2ICvl318h1UxEIhA7LKaanMqBK99dFuWn10/awwwiMKV5qhjk04K9NoLHM2EgOHMOl6FoThiBMWqSayG2Px7EkboinQxnno9VCCx8DdmaAQiSV29L7WwhJL0+2LgkRsL8JtVbOt8cSklXT0t62u3KMOSUOYxrKk51NCK2YmQvhVKWXumw9HcbA/1o0qoZUWf5r+/y/wChzacb0rWf0PwfrBoRTWhWRdwU94y71Qkfp3+2WR5qjjfYcXRF52sLGFT0ol2f8pum1219PQdDc4WmdGZJJqUc/yQ8AJKaMVxqtYallzs2SzmBXwmg9waXYoOJXVEDS8mOwr4K05w6NFZQZuIFQ== root@pve1
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbjvVfYlpQarK/i8WAZ1dr3nhwWTo6JIIR4qfK6A46U5rgRV9fG1tJ04yRSQPoLLMkUlMTd2cCR1U+tTFpy7tMvoHn7EtpZ7cvG2aQSc7o+PoRj/I4eMACnagOBm++57rwO1gVFRcNuLoIDPcXU9EDbXleESPHzWHkMu6uJyf+zXjuHhL7IZuQFzsJUl9ApWD1BiYhDt0Xe40UL9JAPaZr/GMre5YBRk7WApvS65WKVFPTYNNWjeQ5YE8ntpvDjC8LUZ2B7/G5JMJSw61EihRI8Npsavir+EUG46ohy9W/r7vFaCuv5BCLQCB6FhQ+OOLBmdxDCOCkieqSsqqNrX/myaNq9JiCCxY/gbvB5Reql/BENPqijt3cTJuQ0acFSiNVuF+WYRHIYY+VnRgkqTm55AbXhZ/O8EmM6ncb8P/sZvNQz4qGeaJeU3J8aKSxbBy72jxUExdGdhLGA/8bV0nfR8C7zbE0KXmjksVaiD5QeSodLz/NJ9F2BR5LZrnZ1FM0F2MRPkOKuppYRZcuURCV0wr8dzasqcBeDCuPYt6MTuSuXlcMp5EWN6i6HlKtu3fpHwpZkGgAoMAX/BtkGSO9z3ifBiU+a81/5JsAVpsJp4ibdcyp2j3VP9kdai002DYnBesm5iKKb4fQsYHlFfPBSFmVY7LVc0JnmBINuJHq1Q== root@pve2
chpasswd:
  list: |
    ubuntu:ubuntu
  expire: false

