---
pbs_timezone: "Australia/Sydney"
pbs_zfs_arc_max_gb: 8
pbs_zfs_arc_max_bytes: "{{ (pbs_zfs_arc_max_gb * 1024 * 1024 * 1024) | int }}"
pbs_backup_user_email: "fanweiblue@gmail.com"

# PBS credentials (from global vault)
pbs_root_password: "{{ vault_pbs_root_password }}"  # vault indirect reference
pbs_backup_user_password: "{{ vault_pbs_backup_user_password }}"  # vault indirect reference
