---
- name: Apply common baseline to all hosts
  hosts: all
  become: yes
  roles:
    - common

- name: Deploy DevContainer
  import_playbook: deploy-devcontainer.yml
  when: "'devcontainer' in groups['pve_vms']"
