collections:
  - name: community.general
    version: "13.3.0"
  - name: community.vmware
  - name: cloud.terraform
  - name: community.docker
  - name: ansible.posix
  - name: netbox.netbox
  - name: ansible.windows
