
---
# Inventory entry for application VMs.
immich:
  hosts:
    immich:
      ansible_host: 192.168.1.101
      immich_app_dir: /opt/immich
      immich_upload_dir: "{{ immich_app_dir }}/library"
      immich_db_dir: "{{ immich_app_dir }}/postgres"
      immich_env_path: "{{ immich_app_dir }}/.env"
      immich_compose_path: "{{ immich_app_dir }}/docker-compose.yml"
      immich_compose_source: "https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml"
      immich_version: release
      immich_db_username: postgres
      immich_db_name: immich
      immich_db_password: admin

