---
# PBS core setup
- include_tasks: install.yml
  tags: [install]

- include_tasks: configure.yml
  tags: [configure]

- include_tasks: users.yml
  tags: [users]

# ZFS storage setup
- include_tasks: zfs-verify.yml
  tags: [verify, zfs]

- include_tasks: zfs-pool.yml
  tags: [zfs]

- include_tasks: zfs-datastore.yml
  tags: [pbs_datastore]
